bool real_camera
sensor_msgs/PointCloud2 scene_pcd
sensor_msgs/Image depth_img
sensor_msgs/Image color_img
string scene_pcd_save_path
string depth_img_save_path
string color_img_save_path
---
bool success
